# Utiliser une image de base contenant PHP
FROM php:8.1-fpm

# Installation des dépendances système nécessaires pour Laravel et PostgreSQL
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    zip \
    postgresql-client

# Configuration du répertoire de travail dans le conteneur
WORKDIR /var/www/html

# Copier le code source Laravel dans le conteneur
COPY . .

# Installation des dépendances PHP de Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Installation des dépendances du projet Laravel
RUN composer install

# Définir les permissions appropriées sur les répertoires de stockage Laravel
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

# Exposer le port 9000 pour l'exécution de PHP-FPM
EXPOSE 9090

# Commande pour démarrer PHP-FPM lorsqu'un conteneur est lancé
CMD ["php-fpm"]
