name: Continuous integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.x']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Install Vite globally
        run: npm install -g vite

      - name: Build
        run: npm run build
        working-directory: backend
        
      - name: Set permissions for vue-cli-service
        run: chmod a+x node_modules/.bin/vue-cli-service 
        working-directory: vue9

      - name: Install dependencies
        run: npm install
        working-directory: vue9

      - name: Build
        run: npm run build
        working-directory: vue9
        
      - name: Install dependencies for Laravel
        run: npm ci
        working-directory: backend
                
      # Exécuter les tests unitaires Laravel
      - name: Run Laravel unit tests
        run: php artisan test
        working-directory: backend

 # Backend build and tests
      - name: Build and test Laravel backend
        run: |
          docker build -t my-backend-image -f backend/Dockerfile backend
          docker run my-backend-image php artisan test

      # Frontend build and tests
      - name: Build and test Vue.js frontend
        run: |
          docker build -t my-frontend-image -f vue9/Dockerfile vue9
          docker run my-frontend-image npm test

      # Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

       # Build et push de l'image Docker pour le backend
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: backend
          file: backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/laravel-example-backend:latest

      # Build et push de l'image Docker pour le frontend
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: vue9
          file: vue9/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/laravel-example-frontend:latest