name: Continuous integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.x']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Install Vite globally
        run: npm install -g vite

      - name: Build
        run: npm run build
        working-directory: backend

      - name: Test
        run: npx jest
        working-directory: backend

      - name: Install dependencies for Laravel
        run: npm ci
        working-directory: backend
                
      # Exécuter les tests unitaires Laravel
      - name: Run Laravel unit tests
        run: php artisan test
        working-directory: backend

      # Build Docker image
      - name: Build Docker image
        run: docker-compose build
        working-directory: backend

      # Run tests in Docker container
      - name: Run tests in Docker container
        run: docker-compose up
        working-directory: backend

      # Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build et push de l'image Docker
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/.docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/laravel-example:latest