name: Continuous integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.x']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Installation de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Installation des dépendances du projet
      - name: Install project dependencies
        run: npm install
        working-directory: backend
        
      # Construction du projet avec Vite
      - name: Build project with Vite
        run: npx vite build
        working-directory: backend

      # Exécution des tests
      - name: Run tests
        run: npm run test
        working-directory: backend

      # Exécution des tests unitaires Laravel
      - name: Run Laravel unit tests
        run: php artisan test

      # Construction de l'image Docker
      - name: Build Docker image
        run: docker-compose build 
        working-directory: backend

      # Exécution des tests dans le conteneur Docker
      - name: Run tests in Docker container
        run: docker-compose up
        working-directory: backend

      # Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Construction et envoi de l'image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/.docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/laravel-example:latest