name: Continuous deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          password: ${{ secrets.PRODUCTION_SERVER_PASSWORD }}
          script: |
            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/laravel-example-frontend:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/laravel-example-backend:latest

            # Stop the existing container
            docker-compose -f down

            # Remove the old container
            docker-compose rm -f 

            # Recreate and start the container
            docker-compose -f up -d --build --remove-orphans
